import React from 'react';
import { Box, Flex, Text, Grid, GridItem } from '@chakra-ui/react';

const FormalResume = () => {
  return (
    <Box p={12}>
      <Flex direction="column">
        <Text fontSize="4xl" mb={4}>履歴書</Text>
        <Text >2024年</Text>
      </Flex>
      <Grid
        // h='100vh'
        // w='1361px'
        // overflowX="auto"
        templateColumns='repeat(32, 1fr)'
      >
        <GridItem
          colSpan={15}
        >
          <Grid
            templateRows='repeat(32, 1fr)'
            templateColumns='repeat(12, 1fr)'
            border='2px'
          >
            <GridItem
              colSpan={2}
              borderBottom='1px'
            >
              <Text>ふりがな</Text>
            </GridItem>
            <GridItem
              colSpan={6}
              borderRight='1px'
              borderBottom='1px'
            >
              <Text>ハヤシタニ サトシ</Text>
            </GridItem>
            <GridItem
              colSpan={1}
              rowSpan={3}
              borderRight='1px'
              borderBottom='1px'
            >
              <Text>男・女</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              rowSpan={7}
              borderBottom='2px'
            >
              <Text>写真</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              rowSpan={2}
              borderBottom='1px'
            >
              <Text>氏名</Text>
            </GridItem>
            <GridItem
              colSpan={6}
              rowSpan={2}
              borderRight='1px'
              borderBottom='1px'
            >
              <Text>林谷 智史</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
            >
              <Text>生年月日</Text>
            </GridItem>
            <GridItem
              colSpan={7}
              borderRight='1px'
              borderBottom='1px'
            >
              <Text>1992年8月21日(満31歳)</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
            >
              <Text>ふりがな</Text>
            </GridItem>
            <GridItem
              colSpan={7}
              borderRight='1px'
              borderBottom='1px'
            >
              <Text>ホッカイドウサッポロシアツベツクカミノッポロ</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              rowSpan={1}
            >
              <Text>現住所</Text>
            </GridItem>
            <GridItem
              colSpan={7}
              rowSpan={1}
              borderRight='1px'
            >
              <Text>(〒004-0031)</Text>
            </GridItem>
            <GridItem
              colSpan={9}
              borderRight='1px'
              borderBottom='2px'
            >
              <Text>北海道札幌市厚別区上野幌1条1丁目5-8</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='3px double'
              borderRight='1px'
              textAlign='center'
            >
              <Text>年</Text>
            </GridItem>
            <GridItem
              colSpan={1}
              borderBottom='3px double'
              borderRight='1px'
              textAlign='center'
            >
              <Text>月</Text>
            </GridItem>
            <GridItem
              colSpan={9}
              borderBottom='3px double'
              textAlign='center'
            >
              <Text>学歴・職歴</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={1}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={9}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={1}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={9}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={1}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={9}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={1}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={9}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={1}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={9}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={1}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={9}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={1}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={9}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={1}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={9}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
          </Grid>
        </GridItem>
        <GridItem
          colSpan={2}
        >
        </GridItem>
        <GridItem
          colSpan={15}
        >
          <Grid
            templateRows='repeat(32, 1fr)'
            templateColumns='repeat(16, 1fr)'
            border='2px'
          >
            <GridItem
              colSpan={3}
              borderBottom="3px double"
              borderRight='1px'
              textAlign='center'
            >
              <Text>年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom="3px double"
              borderRight='1px'
              textAlign='center'
            >
              <Text>月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom="3px double"
              textAlign='center'
            >
              <Text>学歴・職歴</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='2px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='2px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='2px'
              textAlign='center'
            >
              <Text>スーパーアルティメット大学卒業</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom="3px double"
              borderRight='1px'
              textAlign='center'
            >
              <Text>年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom="3px double"
              borderRight='1px'
              textAlign='center'
            >
              <Text>月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom="3px double"
              textAlign='center'
            >
              <Text>免許・資格</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>ケイン・コスギ監修 SASUKE検定 準8級取得</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>ケイン・コスギ監修 SASUKE検定 準8級取得</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>ケイン・コスギ監修 SASUKE検定 準8級取得</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>ケイン・コスギ監修 SASUKE検定 準8級取得</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>ケイン・コスギ監修 SASUKE検定 準8級取得</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>ケイン・コスギ監修 SASUKE検定 準8級取得</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>ケイン・コスギ監修 SASUKE検定 準8級取得</Text>
            </GridItem>
            <GridItem
              colSpan={3}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>2011年</Text>
            </GridItem>
            <GridItem
              colSpan={2}
              borderBottom='1px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>3月</Text>
            </GridItem>
            <GridItem
              colSpan={11}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>ケイン・コスギ監修 SASUKE検定 準8級取得</Text>
            </GridItem>
            <GridItem
              rowSpan={6}
              colSpan={10}
              borderRight='1px'
              borderBottom='2px'
            >
              <Text>志望の動機、自己PR、趣味、特技など</Text>
            </GridItem>
            <GridItem
              rowSpan={1}
              colSpan={6}
            >
              <Text>通勤時間</Text>
            </GridItem>
            <GridItem
              rowSpan={1}
              colSpan={6}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>約1時間30分</Text>
            </GridItem>
            <GridItem
              rowSpan={1}
              colSpan={6}
            >
              <Text>扶養家族(配偶者を除く)</Text>
            </GridItem>
            <GridItem
              rowSpan={1}
              colSpan={6}
              borderBottom='1px'
              textAlign='center'
            >
              <Text>300人</Text>
            </GridItem>
            <GridItem
              rowSpan={1}
              colSpan={3}
              borderRight='1px'
            >
              <Text>配偶者</Text>
            </GridItem>
            <GridItem
              rowSpan={1}
              colSpan={3}
            >
              <Text>扶養義務</Text>
            </GridItem>
            <GridItem
              rowSpan={1}
              colSpan={3}
              borderBottom='2px'
              borderRight='1px'
              textAlign='center'
            >
              <Text>無</Text>
            </GridItem>
            <GridItem
              rowSpan={1}
              colSpan={3}
              borderBottom='2px'
              textAlign='center'
            >
              <Text>無</Text>
            </GridItem>
            <GridItem
              // rowSpan={6}
              colSpan={16}
              // borderRight='1px'
              // borderBottom='2px'
              borderBottom='3px double'
            >
              <Text>本人希望記入欄(特に待遇・職種・勤務時間・その他についての希望などがあれば記入)</Text>
            </GridItem>
          </Grid>
        </GridItem>
      </Grid>
    </Box>
  );
};

export default FormalResume;
